services:                     # representing a computing resource
  base:
    build: ./base/            # 
    image: ansible_base       # built image name
  master:
    links:                    # defines a network link to containers in another service
      - base
    build: ./master/
    image: ansible_master
    container_name: master01
    hostname: master01                  # hostname declares a custom host name to use for the service container.
    command: ["/usr/sbin/sshd","-D"]
    volumes:
      - ansible_vol:/var/ans
  host:
    links:
      - base
      - master
    build: ./host/
    image: ansible_host
    container_name: host01
    hostname: host01
    command: bash -c "/var/run.sh"
    volumes:
     - ansible_vol:/var/ans   # volume mount at /var/ans
  host02:
    links:
      - base
      - master
      - host
    image: ansible_host
    container_name: host02
    hostname: host02
    #command: ["/var/run.sh"]
    command: bash -c "/var/run.sh"
    volumes:
     - ansible_vol:/var/ans
  # host03:
  #   links:
  #     - base
  #     - master
  #     - host
  #   image: ansible_host
  #   container_name: host03
  #   hostname: host03
  #   command: ["/var/run.sh"]
  #   volumes:
  #    - ansible_vol:/var/ans
volumes:
  ansible_vol:        # a volume across multiple services